<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>

    <!-- Копируем зависимости для nanoCAD -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <!-- Отключаем генерацию лишних конфигов -->
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <!-- Ссылки на библиотеки nanoCAD 25.0 -->
    <Reference Include="hostdbmgd">
      <HintPath>C:\Program Files\Nanosoft\nanoCAD x64 25.0\bin\hostdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="hostmgd">
      <HintPath>C:\Program Files\Nanosoft\nanoCAD x64 25.0\bin\hostmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>